export type RoomErrorCode =
  | 'VALIDATION_ERROR'
  | 'ROOM_NOT_FOUND'
  | 'ROOM_CLOSED'
  | 'ROOM_LOCKED'
  | 'ROOM_FULL'
  | 'PLAYER_ALREADY_EXISTS'
  | 'PLAYER_NOT_FOUND'
  | 'NOT_HOST'
  | 'CANNOT_KICK_SELF'
  | 'RECONNECT_EXPIRED'
  | 'RECONNECT_INVALID_TOKEN'
  | 'MATCH_IN_PROGRESS'
  | 'ROOM_CODE_GENERATION_FAILED'
  | 'CONNECTION_FAILED'
  | 'RATE_LIMITED'
  | 'ROOM_ENTRY_IN_PROGRESS'
  | 'INTERNAL_ERROR';

export type RoomError = {
  code: RoomErrorCode;
  message: string;
};
