export const DEFAULT_GAME_SHELL_COUNTDOWN_SECONDS = 3;
export const DEFAULT_GAME_SHELL_TIMER_SECONDS = 60;
export const DEFAULT_GAME_SHELL_LOBBY_WAIT_MS = 1500;
export const DEFAULT_PLAYER_RECOVERY_SECONDS = 120;
