export const ADMIN_COPY = {
  panelTitle: 'لوحة الإدارة',
  loginTitle: 'تسجيل الدخول للإدارة',
  accessDenied: 'غير مصرح لك بالدخول إلى لوحة الإدارة.',
  emailLabel: 'البريد الإلكتروني',
  passwordLabel: 'كلمة المرور',
  loginCta: 'تسجيل الدخول',
  logout: 'تسجيل الخروج',
  resolving: 'جاري التحقق…',
  navLabel: 'تنقل لوحة الإدارة',
  openNav: 'فتح القائمة',
  closeNav: 'إغلاق القائمة',
  refresh: 'تحديث',
  loadFailed: 'تعذر تحميل بيانات لوحة الإدارة.',
  retry: 'إعادة المحاولة',
  summary: 'ملخص',
  liveRooms: 'الغرف الحالية',
  recentMatches: 'آخر المباريات',
  games: 'الألعاب',
  recentUsers: 'أحدث المستخدمين',
  emptyRooms: 'لا توجد غرف نشطة حالياً',
  emptyMatches: 'لا توجد مباريات بعد',
  emptyUsers: 'لا يوجد مستخدمون بعد',
  lobby: 'في اللوبي',
  inGame: 'داخل لعبة',
  registeredUsers: 'المستخدمون',
  currentRooms: 'الغرف',
  currentSeats: 'المقاعد الحالية',
  connectedPlayers: 'المتصلون',
  disconnectedPlayers: 'المنقطعون',
  spectators: 'المتفرجون',
  completedMatches: 'مباريات مكتملة',
  abortedMatches: 'مباريات ملغاة',
  matchesToday: 'مباريات اليوم (UTC)',
  roomsWithLiveGame: 'غرف داخل لعبة',
  completed: 'مكتملة',
  aborted: 'ملغاة',
  total: 'المجموع',
  locked: 'مقفلة',
  open: 'مفتوحة',
  winners: 'الفائز',
  roomsTitle: 'الغرف الحالية',
  roomDetails: 'تفاصيل الغرفة',
  backToRooms: 'العودة إلى الغرف',
  openRoom: 'فتح التفاصيل',
  lockRoom: 'قفل الغرفة',
  unlockRoom: 'فتح الغرفة',
  kickPlayer: 'طرد',
  kickConfirm: 'طرد هذا اللاعب من الغرفة؟',
  closeRoom: 'إغلاق الغرفة',
  closeConfirmTitle: 'إغلاق الغرفة؟',
  closeConfirmCta: 'نعم، أغلق الغرفة',
  confirm: 'تأكيد',
  cancel: 'إلغاء',
  host: 'المضيف',
  players: 'اللاعبون',
  spectator: 'متفرج',
  connected: 'متصل',
  disconnected: 'منقطع',
  actionFailed: 'تعذر تنفيذ العملية.',
  roomMissing: 'الغرفة غير موجودة.',
  capacity: 'السعة',
  experimentalSettings: 'إعدادات تجريبية',
  gameEnabled: 'مفعلة',
  gameDisabled: 'متوقفة',
  usersTitle: 'المستخدمون',
  historyTitle: 'سجل المباريات',
  userDetails: 'تفاصيل المستخدم',
  matchDetails: 'تفاصيل المباراة',
  backToUsers: 'العودة إلى المستخدمين',
  backToHistory: 'العودة إلى السجل',
  searchLabel: 'بحث',
  searchPlaceholder: 'البريد أو الاسم',
  searchCta: 'بحث',
  previousPage: 'السابق',
  nextPage: 'التالي',
  pageLabel: 'صفحة',
  matchCount: 'المشاركات',
  lastMatch: 'آخر مباراة',
  accountCreated: 'تاريخ الإنشاء',
  historicalName: 'الاسم في المباراة',
  emptyHistory: 'لا توجد مباريات في السجل',
  emptyUserMatches: 'لا توجد مشاركات سابقة',
  userMissing: 'المستخدم غير موجود.',
  matchMissing: 'المباراة غير موجودة.',
  guestParticipant: 'ضيف',
  linkedAccount: 'حساب مرتبط',
  openUser: 'فتح المستخدم',
  openMatch: 'فتح المباراة',
  allGames: 'كل الألعاب',
  allStatuses: 'كل الحالات',
  score: 'النقاط',
  rank: 'الترتيب',
  team: 'الفريق',
  winner: 'فائز',
  activeMatchNote: 'سجل المباراة الجارية لا يمثل حالة اللعب الحية.',
  systemTitle: 'حالة النظام',
  serverStatus: 'حالة السيرفر',
  databaseStatus: 'قاعدة البيانات',
  uptime: 'مدة التشغيل',
  currentConnections: 'الاتصالات الحالية',
  liveGames: 'الألعاب الجارية',
  recordedActiveMatches: 'المباريات المسجلة كجارية',
  memoryUsage: 'استخدام الذاكرة',
  reachable: 'متصلة',
  unreachable: 'غير متصلة',
  serverOk: 'تعمل',
  analyticsTitle: 'التحليلات',
  overview: 'نظرة عامة',
  gameUsage: 'استخدام الألعاب',
  activity: 'النشاط',
  participation: 'المشاركة',
  range24h: 'آخر 24 ساعة',
  range7d: 'آخر 7 أيام',
  range30d: 'آخر 30 يوم',
  rangeAll: 'كل الوقت',
  rangeUtcNote: 'التجميع حسب التوقيت العالمي (UTC).',
  roomsCreated: 'الغرف المنشأة',
  joinCount: 'مرات الانضمام',
  spectatorJoins: 'دخول المتفرجين',
  reconnectSuccess: 'عمليات إعادة الاتصال الناجحة',
  roomsClosed: 'الغرف المغلقة',
  matchesStarted: 'الألعاب التي بدأت',
  matchesCompleted: 'الألعاب المكتملة',
  matchesAborted: 'الألعاب الملغاة',
  completionRate: 'نسبة الاكتمال',
  activeMatchRecords: 'سجلات مباريات بحالة جارية',
  totalParticipations: 'إجمالي المشاركات',
  averageParticipants: 'متوسط المشاركين لكل مباراة',
  emptyPeriod: 'لا توجد بيانات في هذه الفترة',
  started: 'بدأت',
  day: 'اليوم',
} as const;

export const ADMIN_ROLE_LABEL: Record<string, string> = {
  USER: 'مستخدم',
  ADMIN: 'إدارة',
};

export const ADMIN_GAME_TITLES: Record<string, string> = {
  'bara-al-salafa': 'برا السالفة',
  'draw-guess': 'ارسم وخمن',
  'imposter-draw': 'الإمبوستر بالرسم',
  'timing-challenge': 'تحدي التوقيت',
  'who-wrote-it': 'من كتبها؟',
  judge: 'القاضي',
  'guessing-challenge': 'تحدي التخمين',
  'fast-answer': 'أسرع إجابة',
};

export const ADMIN_MATCH_STATUS_LABEL: Record<string, string> = {
  ACTIVE: 'جارية',
  COMPLETED: 'مكتملة',
  ABORTED: 'أُلغيت',
};
