export const ADMIN_COPY = {
  mfaTitle: 'التحقق بخطوتين',
  mfaDescription: 'أدخل رمز تطبيق المصادقة أو استخدم رمز استرداد.',
  mfaMethodLabel: 'طريقة التحقق',
  mfaCodeLabel: 'رمز التحقق',
  mfaCodePlaceholder: '000000',
  mfaRecoveryLabel: 'رمز الاسترداد',
  mfaRecoveryPlaceholder: 'أدخل رمز الاسترداد',
  mfaTotpOption: 'تطبيق المصادقة',
  mfaRecoveryOption: 'رمز استرداد',
  mfaVerifyCta: 'تحقق وسجّل الدخول',
  mfaBack: 'العودة لتسجيل الدخول',
  mfaInvalidCode: 'أدخل رمز تحقق صالحًا.',
  mfaVerificationFailed: 'تعذر التحقق من الرمز. تأكد منه وحاول مرة أخرى.',
  panelTitle: 'لوحة الإدارة',
  loginTitle: 'تسجيل الدخول للإدارة',
  accessDenied: 'غير مصرح لك بالدخول إلى لوحة الإدارة.',
  emailLabel: 'البريد الإلكتروني',
  passwordLabel: 'كلمة المرور',
  loginCta: 'تسجيل الدخول',
  logout: 'تسجيل الخروج',
  resolving: 'جاري التحقق…',
  navLabel: 'تنقل لوحة الإدارة',
  openNav: 'فتح القائمة',
  closeNav: 'إغلاق القائمة',
  refresh: 'تحديث',
  loadFailed: 'تعذر تحميل بيانات لوحة الإدارة.',
  retry: 'إعادة المحاولة',
  summary: 'ملخص',
  liveRooms: 'الغرف الحالية',
  recentMatches: 'آخر المباريات',
  games: 'الألعاب',
  recentUsers: 'أحدث المستخدمين',
  emptyRooms: 'لا توجد غرف نشطة حالياً',
  emptyMatches: 'لا توجد مباريات بعد',
  emptyUsers: 'لا يوجد مستخدمون بعد',
  lobby: 'في اللوبي',
  inGame: 'داخل لعبة',
  registeredUsers: 'المستخدمون',
  currentRooms: 'الغرف',
  currentSeats: 'المقاعد الحالية',
  connectedPlayers: 'المتصلون',
  disconnectedPlayers: 'المنقطعون',
  spectators: 'المتفرجون',
  completedMatches: 'مباريات مكتملة',
  abortedMatches: 'مباريات ملغاة',
  matchesToday: 'مباريات اليوم (UTC)',
  roomsWithLiveGame: 'غرف داخل لعبة',
  completed: 'مكتملة',
  aborted: 'ملغاة',
  total: 'المجموع',
  locked: 'مقفلة',
  open: 'مفتوحة',
  winners: 'الفائز',
  roomsTitle: 'الغرف المباشرة',
  roomDetails: 'تفاصيل الغرفة',
  backToRooms: 'العودة إلى الغرف',
  openRoom: 'فتح التفاصيل',
  lockRoom: 'قفل الغرفة',
  unlockRoom: 'فتح الغرفة',
  kickPlayer: 'طرد',
  kickConfirm: 'طرد هذا اللاعب من الغرفة؟',
  kickConfirmCta: 'طرد اللاعب',
  closeRoom: 'إغلاق الغرفة',
  closeConfirmTitle: 'إغلاق الغرفة؟',
  closeConfirmCta: 'نعم، أغلق الغرفة',
  spectateLive: 'مشاهدة مباشرة',
  spectateTitle: 'مشاهدة مباشرة',
  spectateBanner: 'وضع المشاهدة — مسؤول',
  spectateReadOnly: 'عرض للقراءة فقط. لا يمكنك المشاركة أو تغيير حالة الغرفة.',
  spectateBackToAdmin: 'العودة إلى الإدارة',
  spectateConnecting: 'جاري الاتصال بجلسة المشاهدة…',
  spectateDisconnected: 'انقطع الاتصال',
  spectateClosed: 'أُغلقت الغرفة',
  spectateClosedHint: 'لم تعد هذه الغرفة نشطة. يمكنك العودة إلى لوحة الإدارة.',
  spectateDenied: 'غير مصرح لك بمشاهدة هذه الغرفة.',
  spectateUnavailable: 'تعذر بدء المشاهدة المباشرة.',
  spectateLobbyState: 'الغرفة في اللوبي',
  spectateNoRuntime: 'حالة اللعب غير متاحة للعرض حالياً.',
  spectateScoreboard: 'النتائج',
  spectateConnectionLive: 'متصل',
  spectateConnectionLost: 'غير متصل',
  confirm: 'تأكيد',
  cancel: 'إلغاء',
  host: 'المضيف',
  players: 'اللاعبون',
  spectator: 'متفرج',
  connected: 'متصل',
  disconnected: 'منقطع',
  actionFailed: 'تعذر تنفيذ العملية.',
  roomMissing: 'الغرفة غير موجودة.',
  capacity: 'السعة',
  experimentalSettings: 'إعدادات تجريبية',
  gameEnabled: 'مفعلة',
  gameDisabled: 'متوقفة',
  usersTitle: 'المستخدمون',
  historyTitle: 'سجل المباريات',
  roomHistoryTitle: 'سجل الغرف',
  roomHistoryDetails: 'تفاصيل سجل الغرفة',
  backToRoomHistory: 'العودة إلى سجل الغرف',
  emptyRoomHistory: 'لا توجد غرف مطابقة في السجل',
  roomHistoryMissing: 'سجل الغرفة غير موجود.',
  partialHistory: 'سجل جزئي',
  completeHistory: 'سجل مكتمل',
  partialHistoryNote:
    'بدأ التتبع بعد إنشاء الغرفة؛ قد تكون بعض معلومات المضيفين والمشاركين غير مكتملة.',
  originalHost: 'المضيف الأصلي',
  finalHost: 'المضيف النهائي/الحالي',
  historyStarted: 'بداية التتبع',
  closedAt: 'وقت الإغلاق',
  closeReason: 'سبب الإغلاق',
  hostHistory: 'سجل المضيفين',
  participantHistory: 'سجل المشاركين',
  roomMatches: 'المباريات داخل الغرفة',
  joinedAt: 'وقت الانضمام',
  leftAt: 'وقت المغادرة',
  unknown: 'غير معروف',
  historicalOpen: 'مفتوحة تاريخياً',
  historicalClosed: 'مغلقة',
  allRoomStates: 'كل حالات الغرف',
  roomCodeSearch: 'رمز الغرفة',
  participantSearch: 'اسم المشارك',
  hostSearch: 'اسم المضيف',
  createdFrom: 'أُنشئت من',
  createdTo: 'أُنشئت حتى',
  clearFilters: 'مسح الفلاتر',
  lockState: 'حالة القفل',
  allLockStates: 'كل حالات القفل',
  createdByAdmin: 'أنشأتها الإدارة',
  liveRoomLink: 'فتح الحالة المباشرة',
  noHostAssignments: 'لا تتوفر تعيينات مضيف مسجلة',
  noParticipants: 'لا تتوفر مشاركات مسجلة',
  noRoomMatches: 'لا توجد مباريات مرتبطة بهذا السجل',
  userDetails: 'تفاصيل المستخدم',
  matchDetails: 'تفاصيل المباراة',
  backToUsers: 'العودة إلى المستخدمين',
  backToHistory: 'العودة إلى السجل',
  searchLabel: 'بحث',
  searchPlaceholder: 'البريد أو الاسم',
  searchCta: 'بحث',
  previousPage: 'السابق',
  nextPage: 'التالي',
  pageLabel: 'صفحة',
  matchCount: 'المشاركات',
  lastMatch: 'آخر مباراة',
  accountCreated: 'تاريخ الإنشاء',
  historicalName: 'الاسم في المباراة',
  emptyHistory: 'لا توجد مباريات في السجل',
  auditLogsTitle: 'سجل التدقيق',
  emptyAuditLogs: 'لا توجد سجلات تدقيق',
  unknownAction: 'إجراء غير معروف',
  auditActor: 'المسؤول',
  auditAction: 'الإجراء',
  auditTarget: 'المورد',
  auditOutcome: 'النتيجة',
  auditDetails: 'التفاصيل',
  auditTime: 'الوقت',
  auditRequestId: 'معرّف الطلب',
  auditOutcomeSuccess: 'نجاح',
  auditOutcomeFailure: 'فشل',
  auditTargetUser: 'مستخدم',
  auditTargetGame: 'لعبة',
  auditTargetRoom: 'غرفة',
  emptyUserMatches: 'لا توجد مشاركات سابقة',
  userMissing: 'المستخدم غير موجود.',
  matchMissing: 'المباراة غير موجودة.',
  guestParticipant: 'ضيف',
  linkedAccount: 'حساب مرتبط',
  openUser: 'فتح المستخدم',
  openMatch: 'فتح المباراة',
  allGames: 'كل الألعاب',
  allStatuses: 'كل الحالات',
  score: 'النقاط',
  rank: 'الترتيب',
  team: 'الفريق',
  winner: 'فائز',
  activeMatchNote: 'سجل المباراة الجارية لا يمثل حالة اللعب الحية.',
  systemTitle: 'حالة النظام',
  serverStatus: 'حالة السيرفر',
  databaseStatus: 'قاعدة البيانات',
  uptime: 'مدة التشغيل',
  currentConnections: 'الاتصالات الحالية',
  liveGames: 'الألعاب الجارية',
  recordedActiveMatches: 'المباريات المسجلة كجارية',
  memoryUsage: 'استخدام الذاكرة',
  reachable: 'متصلة',
  unreachable: 'غير متصلة',
  serverOk: 'تعمل',
  analyticsTitle: 'التحليلات',
  overview: 'نظرة عامة',
  gameUsage: 'استخدام الألعاب',
  activity: 'النشاط',
  participation: 'المشاركة',
  range24h: 'آخر 24 ساعة',
  range7d: 'آخر 7 أيام',
  range30d: 'آخر 30 يوم',
  rangeAll: 'كل الوقت',
  rangeUtcNote: 'التجميع حسب توقيت السعودية (Asia/Riyadh).',
  roomsCreated: 'الغرف المنشأة',
  joinCount: 'مرات الانضمام',
  spectatorJoins: 'دخول المتفرجين',
  reconnectSuccess: 'عمليات إعادة الاتصال الناجحة',
  roomsClosed: 'الغرف المغلقة',
  matchesStarted: 'الألعاب التي بدأت',
  matchesCompleted: 'الألعاب المكتملة',
  matchesAborted: 'الألعاب الملغاة',
  completionRate: 'نسبة الاكتمال',
  activeMatchRecords: 'سجلات مباريات بحالة جارية',
  totalParticipations: 'إجمالي المشاركات',
  averageParticipants: 'متوسط المشاركين لكل مباراة',
  emptyPeriod: 'لا توجد بيانات في هذه الفترة',
  started: 'بدأت',
  day: 'اليوم',
} as const;

export const ADMIN_ROLE_LABEL: Record<string, string> = {
  USER: 'مستخدم',
  ADMIN: 'إدارة',
};

export const ADMIN_GAME_TITLES: Record<string, string> = {
  'bara-al-salafa': 'برا السالفة',
  'draw-guess': 'ارسم وخمن',
  'imposter-draw': 'الإمبوستر بالرسم',
  'timing-challenge': 'تحدي التوقيت',
  'who-wrote-it': 'من كتبها؟',
  judge: 'القاضي',
  'guessing-challenge': 'تحدي التخمين',
  'fast-answer': 'أسرع إجابة',
};

export const ADMIN_MATCH_STATUS_LABEL: Record<string, string> = {
  ACTIVE: 'جارية',
  COMPLETED: 'مكتملة',
  ABORTED: 'أُلغيت',
};

export const ADMIN_ROOM_CLOSE_REASON_LABEL: Record<string, string> = {
  ROOM_EMPTY: 'أصبحت الغرفة فارغة',
  HOST_ENDED: 'أنهى المضيف الغرفة',
  ADMIN_FORCE_CLOSED: 'أغلقتها الإدارة',
  STARTUP_RECONCILIATION: 'تسوية بعد إعادة تشغيل الخادم',
};

export const ADMIN_AUDIT_ACTION_LABEL: Record<string, string> = {
  ROLE_PROMOTED: 'تغيير صلاحيات',
  MFA_ENROLLMENT_STARTED: 'بدء تفعيل التحقق بخطوتين',
  MFA_ENABLED: 'تفعيل التحقق بخطوتين',
  MFA_LOGIN_SUCCESS: 'تسجيل دخول',
  MFA_LOGIN_FAILURE: 'فشل تسجيل الدخول',
  MFA_RECOVERY_USED: 'استخدام رمز استرداد',
  GAME_AVAILABILITY_SET: 'إعدادات لعبة',
  ROOM_LOCK: 'قفل غرفة',
  ROOM_UNLOCK: 'فتح غرفة',
  ROOM_KICK: 'طرد لاعب',
  ROOM_FORCE_CLOSE: 'إغلاق غرفة',
  ROOM_SPECTATE: 'مشاهدة مباشرة',
};

export const ADMIN_AUDIT_METADATA_LABEL: Record<string, string> = {
  source: 'المصدر',
  keyVersion: 'إصدار المفتاح',
  recoveryCodeCount: 'عدد رموز الاسترداد',
  method: 'الطريقة',
  reason: 'السبب',
  isEnabled: 'مفعّلة',
  isLocked: 'مقفلة',
  playerId: 'معرّف اللاعب',
  roomDeleted: 'حُذفت الغرفة',
  alreadyClosed: 'كانت مغلقة مسبقاً',
};
